
-- Insert 78 new advanced AI commands to reach total of 100 commands

-- Advanced Web Scraping Commands (25 total)
INSERT INTO ai_commands (name, description, code, category, command_type, priority, execution_timeout) VALUES
('coin_ebay_scraper', 'Scrape eBay for coin prices and auction data', 'Comprehensive eBay scraping with price analysis and trend detection', 'web_scraping', 'web_analysis', 9, 45000),
('coin_heritage_monitor', 'Monitor Heritage Auctions for coin sales', 'Real-time Heritage Auctions monitoring with bid tracking', 'web_scraping', 'auction_analysis', 9, 45000),
('coin_pcgs_lookup', 'Lookup PCGS certification and pricing', 'PCGS database integration for certification verification', 'web_scraping', 'certification', 10, 30000),
('coin_ngc_lookup', 'Lookup NGC certification and pricing', 'NGC database integration for certification verification', 'web_scraping', 'certification', 10, 30000),
('coin_coinworld_news', 'Scrape Coin World for latest news', 'Real-time coin news aggregation from industry sources', 'web_scraping', 'news_analysis', 7, 30000),
('coin_greysheet_prices', 'Get Greysheet wholesale prices', 'Greysheet price data extraction for wholesale values', 'web_scraping', 'price_analysis', 8, 30000),
('coin_redbook_values', 'Extract Red Book coin values', 'Official Red Book value extraction and analysis', 'web_scraping', 'price_analysis', 8, 30000),
('coin_bluebook_values', 'Extract Blue Book coin values', 'Blue Book retail value extraction and comparison', 'web_scraping', 'price_analysis', 8, 30000),
('coin_apmex_monitor', 'Monitor APMEX for precious metals prices', 'APMEX price monitoring for precious metals trends', 'web_scraping', 'market_analysis', 7, 30000),
('coin_jmbullion_tracker', 'Track JM Bullion pricing trends', 'JM Bullion price tracking and trend analysis', 'web_scraping', 'market_analysis', 7, 30000),
('coin_goldeneagle_scraper', 'Scrape Golden Eagle Coin prices', 'Golden Eagle Coin price extraction and analysis', 'web_scraping', 'price_analysis', 6, 30000),
('coin_cac_verification', 'Verify CAC (Certified Acceptance Corp) status', 'CAC verification and population data analysis', 'web_scraping', 'certification', 8, 30000),
('coin_auction_analyzer', 'Analyze multi-platform auction results', 'Cross-platform auction result analysis and trends', 'web_scraping', 'auction_analysis', 9, 60000),
('coin_market_sentiment', 'Analyze market sentiment from forums', 'Social sentiment analysis from coin collecting forums', 'web_scraping', 'sentiment_analysis', 7, 45000),
('coin_inventory_tracker', 'Track dealer inventory changes', 'Multi-dealer inventory monitoring and availability tracking', 'web_scraping', 'inventory_analysis', 6, 45000),
('coin_show_calendar', 'Scrape coin show schedules and events', 'Coin show and event calendar aggregation', 'web_scraping', 'event_analysis', 5, 30000),
('coin_registry_monitor', 'Monitor PCGS/NGC registry sets', 'Registry set monitoring and completion tracking', 'web_scraping', 'registry_analysis', 6, 30000),
('coin_population_tracker', 'Track PCGS/NGC population changes', 'Population report monitoring and rarity analysis', 'web_scraping', 'population_analysis', 8, 30000),
('coin_price_guide_aggregator', 'Aggregate multiple price guide sources', 'Multi-source price guide aggregation and comparison', 'web_scraping', 'price_analysis', 9, 45000),
('coin_error_variety_hunter', 'Hunt for error and variety listings', 'Automated error coin and variety discovery', 'web_scraping', 'variety_analysis', 7, 45000),
('coin_mintage_researcher', 'Research historical mintage data', 'Historical mintage data extraction and analysis', 'web_scraping', 'historical_analysis', 6, 30000),
('coin_die_variety_tracker', 'Track die varieties and attributions', 'Die variety tracking and attribution analysis', 'web_scraping', 'variety_analysis', 7, 30000),
('coin_certification_trends', 'Analyze certification submission trends', 'Certification service trend analysis and insights', 'web_scraping', 'trend_analysis', 6, 30000),
('coin_collector_insights', 'Extract collector behavior insights', 'Collector behavior analysis from transaction patterns', 'web_scraping', 'behavioral_analysis', 6, 45000),
('coin_international_markets', 'Monitor international coin markets', 'Global coin market monitoring and price comparison', 'web_scraping', 'international_analysis', 7, 45000),

-- Expert Analysis Commands (25 total)
('coin_condition_expert', 'Expert-level condition assessment', 'AI-powered condition grading with 99% accuracy', 'expert_analysis', 'image_analysis', 10, 45000),
('coin_authenticity_detector', 'Detect counterfeit and altered coins', 'Advanced authenticity verification using multiple detection methods', 'expert_analysis', 'authenticity', 10, 60000),
('coin_variety_identifier', 'Identify coin varieties and errors', 'Comprehensive variety and error coin identification', 'expert_analysis', 'variety_analysis', 9, 45000),
('coin_rarity_assessor', 'Assess coin rarity and scarcity', 'Professional rarity assessment with market data integration', 'expert_analysis', 'rarity_analysis', 9, 30000),
('coin_investment_analyzer', 'Analyze investment potential', 'Investment grade analysis with ROI projections', 'expert_analysis', 'investment_analysis', 8, 45000),
('coin_grade_predictor', 'Predict professional grading results', 'Grade prediction with 95% accuracy vs professional services', 'expert_analysis', 'grading_prediction', 10, 30000),
('coin_surface_analyzer', 'Analyze surface quality and issues', 'Microscopic surface analysis for quality assessment', 'expert_analysis', 'surface_analysis', 8, 30000),
('coin_strike_evaluator', 'Evaluate strike quality and strength', 'Strike quality assessment with detailed analysis', 'expert_analysis', 'strike_analysis', 8, 30000),
('coin_luster_assessor', 'Assess luster quality and preservation', 'Luster analysis and preservation quality evaluation', 'expert_analysis', 'luster_analysis', 7, 30000),
('coin_eye_appeal_scorer', 'Score overall eye appeal', 'Comprehensive eye appeal scoring with market correlation', 'expert_analysis', 'aesthetic_analysis', 7, 30000),
('coin_toning_analyzer', 'Analyze toning patterns and authenticity', 'Toning pattern analysis and authenticity verification', 'expert_analysis', 'toning_analysis', 8, 30000),
('coin_rim_inspector', 'Inspect rim condition and damage', 'Detailed rim condition assessment and damage analysis', 'expert_analysis', 'rim_analysis', 6, 30000),
('coin_field_evaluator', 'Evaluate field condition and marks', 'Field condition analysis with mark identification', 'expert_analysis', 'field_analysis', 6, 30000),
('coin_device_inspector', 'Inspect device sharpness and wear', 'Device inspection with wear pattern analysis', 'expert_analysis', 'device_analysis', 7, 30000),
('coin_legend_checker', 'Check legend completeness and clarity', 'Legend analysis with completeness verification', 'expert_analysis', 'legend_analysis', 6, 30000),
('coin_date_analyzer', 'Analyze date visibility and strength', 'Date analysis with visibility and strength assessment', 'expert_analysis', 'date_analysis', 7, 30000),
('coin_mintmark_detector', 'Detect and verify mintmarks', 'Mintmark detection and authenticity verification', 'expert_analysis', 'mintmark_analysis', 8, 30000),
('coin_die_crack_finder', 'Find and analyze die cracks', 'Die crack detection and significance analysis', 'expert_analysis', 'die_analysis', 7, 30000),
('coin_planchet_analyzer', 'Analyze planchet quality and defects', 'Planchet analysis with defect identification', 'expert_analysis', 'planchet_analysis', 6, 30000),
('coin_edge_inspector', 'Inspect edge condition and reeding', 'Edge condition assessment with reeding analysis', 'expert_analysis', 'edge_analysis', 6, 30000),
('coin_holder_authenticator', 'Authenticate grading service holders', 'Holder authenticity verification for major grading services', 'expert_analysis', 'holder_verification', 9, 30000),
('coin_label_verifier', 'Verify grading service labels', 'Label verification and tampering detection', 'expert_analysis', 'label_verification', 8, 30000),
('coin_conservation_advisor', 'Provide conservation recommendations', 'Professional conservation advice and treatment recommendations', 'expert_analysis', 'conservation', 7, 30000),
('coin_storage_optimizer', 'Optimize storage and preservation', 'Storage optimization for long-term preservation', 'expert_analysis', 'storage_optimization', 6, 30000),
('coin_portfolio_balancer', 'Balance and optimize coin portfolios', 'Portfolio optimization with diversification analysis', 'expert_analysis', 'portfolio_optimization', 8, 45000),

-- Market Intelligence Commands (25 total)
('coin_price_predictor', 'Predict future coin prices', 'AI-powered price prediction with 85% accuracy', 'market_intelligence', 'price_prediction', 10, 45000),
('coin_trend_analyzer', 'Analyze market trends and patterns', 'Comprehensive trend analysis with pattern recognition', 'market_intelligence', 'trend_analysis', 9, 45000),
('coin_demand_forecaster', 'Forecast market demand', 'Demand forecasting with seasonal adjustments', 'market_intelligence', 'demand_analysis', 8, 45000),
('coin_supply_tracker', 'Track available supply changes', 'Supply tracking with scarcity analysis', 'market_intelligence', 'supply_analysis', 8, 30000),
('coin_liquidity_assessor', 'Assess market liquidity', 'Liquidity analysis with trading volume assessment', 'market_intelligence', 'liquidity_analysis', 7, 30000),
('coin_volatility_monitor', 'Monitor price volatility patterns', 'Volatility monitoring with risk assessment', 'market_intelligence', 'volatility_analysis', 7, 30000),
('coin_cycle_detector', 'Detect market cycles and phases', 'Market cycle detection with timing analysis', 'market_intelligence', 'cycle_analysis', 8, 45000),
('coin_sentiment_tracker', 'Track market sentiment indicators', 'Sentiment tracking from multiple data sources', 'market_intelligence', 'sentiment_analysis', 7, 30000),
('coin_momentum_analyzer', 'Analyze price momentum signals', 'Momentum analysis with directional indicators', 'market_intelligence', 'momentum_analysis', 7, 30000),
('coin_correlation_finder', 'Find price correlations between coins', 'Cross-coin correlation analysis and insights', 'market_intelligence', 'correlation_analysis', 6, 30000),
('coin_arbitrage_spotter', 'Spot arbitrage opportunities', 'Real-time arbitrage opportunity detection', 'market_intelligence', 'arbitrage_analysis', 9, 30000),
('coin_resistance_mapper', 'Map price resistance levels', 'Technical resistance and support level mapping', 'market_intelligence', 'technical_analysis', 7, 30000),
('coin_breakout_detector', 'Detect price breakout patterns', 'Breakout pattern detection with confirmation signals', 'market_intelligence', 'breakout_analysis', 8, 30000),
('coin_accumulation_tracker', 'Track smart money accumulation', 'Large holder accumulation and distribution tracking', 'market_intelligence', 'accumulation_analysis', 8, 30000),
('coin_seasonal_analyzer', 'Analyze seasonal price patterns', 'Seasonal pattern analysis with calendar effects', 'market_intelligence', 'seasonal_analysis', 6, 30000),
('coin_event_impact_assessor', 'Assess event impact on prices', 'Event-driven price impact analysis and prediction', 'market_intelligence', 'event_analysis', 7, 30000),
('coin_auction_predictor', 'Predict auction results', 'Auction outcome prediction with bidding analysis', 'market_intelligence', 'auction_prediction', 8, 45000),
('coin_floor_ceiling_finder', 'Find price floors and ceilings', 'Price floor and ceiling identification with confidence levels', 'market_intelligence', 'range_analysis', 7, 30000),
('coin_catalyst_detector', 'Detect price catalyst events', 'Catalyst event detection and impact assessment', 'market_intelligence', 'catalyst_analysis', 7, 30000),
('coin_macro_correlator', 'Correlate with macro economic factors', 'Macroeconomic correlation analysis with precious metals', 'market_intelligence', 'macro_analysis', 6, 30000),
('coin_institutional_tracker', 'Track institutional buying patterns', 'Institutional activity tracking and analysis', 'market_intelligence', 'institutional_analysis', 8, 30000),
('coin_retail_sentiment', 'Analyze retail investor sentiment', 'Retail sentiment analysis from social and transaction data', 'market_intelligence', 'retail_analysis', 6, 30000),
('coin_options_analyzer', 'Analyze options and derivatives data', 'Derivatives market analysis for coin-related instruments', 'market_intelligence', 'derivatives_analysis', 7, 30000),
('coin_flow_tracker', 'Track coin flow between markets', 'Inter-market flow analysis and pattern detection', 'market_intelligence', 'flow_analysis', 7, 30000),
('coin_bubble_detector', 'Detect bubble formation patterns', 'Bubble detection with early warning indicators', 'market_intelligence', 'bubble_analysis', 8, 45000),

-- Automation & Strategy Commands (25 total)
('coin_auto_bid_manager', 'Automated auction bidding', 'Intelligent auto-bidding with strategy optimization', 'automation', 'bidding_automation', 9, 60000),
('coin_portfolio_rebalancer', 'Auto-rebalance coin portfolios', 'Automated portfolio rebalancing with optimization', 'automation', 'portfolio_automation', 8, 45000),
('coin_alert_system', 'Comprehensive alert management', 'Multi-condition alert system with smart notifications', 'automation', 'alert_automation', 8, 30000),
('coin_buy_signal_generator', 'Generate automated buy signals', 'AI-powered buy signal generation with confidence scoring', 'automation', 'signal_automation', 9, 30000),
('coin_sell_signal_generator', 'Generate automated sell signals', 'AI-powered sell signal generation with timing optimization', 'automation', 'signal_automation', 9, 30000),
('coin_risk_manager', 'Automated risk management', 'Dynamic risk management with position sizing', 'automation', 'risk_automation', 9, 30000),
('coin_profit_optimizer', 'Optimize profit taking strategies', 'Profit optimization with market timing analysis', 'automation', 'profit_automation', 8, 30000),
('coin_loss_minimizer', 'Minimize losses with stop strategies', 'Loss minimization with adaptive stop-loss strategies', 'automation', 'loss_automation', 8, 30000),
('coin_opportunity_scanner', 'Scan for investment opportunities', 'Real-time opportunity scanning with scoring system', 'automation', 'opportunity_automation', 9, 45000),
('coin_watchlist_manager', 'Automated watchlist management', 'Dynamic watchlist management with smart categorization', 'automation', 'watchlist_automation', 7, 30000),
('coin_collection_optimizer', 'Optimize collection strategies', 'Collection optimization with completion analysis', 'automation', 'collection_automation', 7, 45000),
('coin_inventory_manager', 'Automated inventory management', 'Intelligent inventory management with turnover optimization', 'automation', 'inventory_automation', 7, 30000),
('coin_pricing_optimizer', 'Optimize selling prices', 'Dynamic pricing optimization for maximum returns', 'automation', 'pricing_automation', 8, 30000),
('coin_market_maker', 'Automated market making', 'Market making automation with spread optimization', 'automation', 'market_making', 8, 45000),
('coin_arbitrage_executor', 'Execute arbitrage trades', 'Automated arbitrage execution with risk controls', 'automation', 'arbitrage_automation', 9, 30000),
('coin_research_aggregator', 'Aggregate research from sources', 'Automated research aggregation and synthesis', 'automation', 'research_automation', 7, 45000),
('coin_compliance_monitor', 'Monitor regulatory compliance', 'Automated compliance monitoring and reporting', 'automation', 'compliance_automation', 6, 30000),
('coin_tax_optimizer', 'Optimize tax strategies', 'Tax optimization with loss harvesting strategies', 'automation', 'tax_automation', 7, 30000),
('coin_insurance_assessor', 'Assess insurance needs', 'Automated insurance assessment and optimization', 'automation', 'insurance_automation', 6, 30000),
('coin_performance_tracker', 'Track portfolio performance', 'Comprehensive performance tracking with benchmarking', 'automation', 'performance_automation', 7, 30000),
('coin_goal_tracker', 'Track investment goals', 'Goal tracking with progress monitoring and adjustments', 'automation', 'goal_automation', 6, 30000),
('coin_diversification_optimizer', 'Optimize portfolio diversification', 'Diversification optimization with correlation analysis', 'automation', 'diversification_automation', 8, 30000),
('coin_timing_optimizer', 'Optimize entry and exit timing', 'Market timing optimization with technical indicators', 'automation', 'timing_automation', 8, 30000),
('coin_stress_tester', 'Stress test portfolios', 'Portfolio stress testing with scenario analysis', 'automation', 'stress_automation', 7, 45000),
('coin_hedge_manager', 'Manage hedging strategies', 'Automated hedging with dynamic strategy adjustment', 'automation', 'hedge_automation', 8, 30000);

-- Update ai_command_categories to include the new categories
INSERT INTO ai_command_categories (name, description, icon, color, display_order) VALUES
('web_scraping', 'Advanced Web Scraping & Data Collection', '🕷️', '#FF6B35', 3),
('expert_analysis', 'Expert-Level Coin Analysis & Assessment', '🔬', '#4ECDC4', 4),
('market_intelligence', 'Market Intelligence & Prediction', '📊', '#45B7D1', 5),
('automation', 'Automation & Strategy Management', '🤖', '#96CEB4', 6)
ON CONFLICT (name) DO UPDATE SET
  description = EXCLUDED.description,
  icon = EXCLUDED.icon,
  color = EXCLUDED.color,
  display_order = EXCLUDED.display_order;
