
name: Enhanced Deploy to Vercel

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    name: Quality & Security Checks
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Check for mock data
      run: |
        echo "🔍 Scanning for mock data..."
        if grep -r "mock\|fake\|dummy\|hardcoded" src/ --include="*.ts" --include="*.tsx" | grep -v "// ... keep existing code"; then
          echo "❌ Mock data detected!"
          exit 1
        fi
        echo "✅ No mock data found"
        
    - name: Run mock validation script
      run: node scripts/validate-no-mocks.js
      
    - name: Lint check
      run: npm run lint || echo "Lint warnings found"
      
    - name: Type check
      run: npm run type-check || npm run build
      
    - name: Security audit
      run: npm audit --audit-level moderate || echo "Security warnings found"
      
  build-test:
    needs: quality-checks
    runs-on: ubuntu-latest
    name: Build & Test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      env:
        # Supabase Configuration (Updated)
        VITE_SUPABASE_URL: https://wdgnllgbfvjgurbqhfqb.supabase.co
        VITE_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndkZ25sbGdiZnZqZ3VyYnFoZnFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNTM4NjUsImV4cCI6MjA2NDYyOTg2NX0.vPsjHXSqpx3SLKtoIroQkFZhTSdWEfHA4x5kg5p1veU
        
        # AI API Keys
        ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        CUSTOM_AI_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        CUSTOM_AI_ENDPOINT: https://api.anthropic.com/v1/messages
        CUSTOM_AI_MODEL: claude-3-sonnet-20240229
        
        # Payment Configuration
        TRANSAK_API_KEY: ${{ secrets.TRANSAK_API_KEY }}
        
    - name: Check build size
      run: |
        echo "📦 Build size analysis:"
        du -sh dist/
        find dist/ -name "*.js" -exec du -h {} \; | sort -hr | head -10
        
  deploy:
    needs: [quality-checks, build-test]
    runs-on: ubuntu-latest
    name: Deploy to Vercel
    if: github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        vercel-args: '--prod'
        working-directory: './'
        
    - name: Post-deployment checks
      run: |
        echo "✅ Deployment completed"
        echo "🔗 Production URL available"
        
    - name: Notify deployment status
      if: always()
      run: |
        if [ "${{ job.status }}" = "success" ]; then
          echo "🎉 Deployment successful!"
        else
          echo "❌ Deployment failed - check logs"
        fi
